app_index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index, template: consulter, onglet: consulter }
    options:
        sitemap: true

app_seance:
    path:      /deroulement-seance-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: seance, onglet: seance }
    options:
        sitemap: true

app_praticien:
    path:      /le-praticien-osteopathe-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: praticien, onglet: praticien }
    options:
        sitemap: true

app_tarif:
    path:      /tarif-et-remboursement-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: tarif, onglet: tarif }
    options:
        sitemap: true

app_contact:
    path:      /contact-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: contact, onglet: contact }
    options:
        sitemap: true

app_adomicile:
    path:      /pour-les-entreprises-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: adomicile, onglet: adomicile }
    options:
        sitemap: true

app_consulter:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017.html
    defaults:  { _controller: AppBundle:Default:index, template: consulter, onglet: consulter }
    options:
        sitemap: true

app_femmes:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017/femmes-enceintes.html
    defaults:  { _controller: AppBundle:Default:index, template: femmes, onglet: femmes }
    options:
        sitemap: true

app_nourrissons:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017/nourrissons.html
    defaults:  { _controller: AppBundle:Default:index, template: nourrissons, onglet: nourrissons }
    options:
        sitemap: true

app_adolescents:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017/enfants-et-adolescents.html
    defaults:  { _controller: AppBundle:Default:index, template: adolescents, onglet: adolescents }
    options:
        sitemap: true

app_adultes:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017/adultes-et-seniors.html
    defaults:  { _controller: AppBundle:Default:index, template: adultes, onglet: adultes }
    options:
        sitemap: true

app_sportifs:
    path:      /quand-consulter-cabinet-osteopathie-paris-75017/sportifs.html
    defaults:  { _controller: AppBundle:Default:index, template: sportifs, onglet: sportifs }
    options:
        sitemap: true

app_test:
    path:     /test.html
    defaults: { _controller: AppBundle:Test:index, h2: false }

app_testh2:
    path:    /testh2.html
    defaults: { _controller: AppBundle:Test:index, h2: true }

