app_index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index, template: consulter, onglet: consulter }

app_seance:
    path:      /deroulement-d-une-seance.html
    defaults:  { _controller: AppBundle:Default:index, template: seance, onglet: seance }

app_praticien:
    path:      /le-praticien-ostéopathe.html
    defaults:  { _controller: AppBundle:Default:index, template: praticien, onglet: praticien }

app_tarif:
    path:      /tarif-et-remboursement.html
    defaults:  { _controller: AppBundle:Default:index, template: tarif, onglet: tarif }

app_consulter:
    path:      /osteopathie-quand-consulter.html
    defaults:  { _controller: AppBundle:Default:index, template: consulter, onglet: consulter }

app_contact:
    path:      /contact.html
    defaults:  { _controller: AppBundle:Default:index, template: contact, onglet: contact }

app_adomicile:
    path:      /ostéopathie-entreprise.html
    defaults:  { _controller: AppBundle:Default:index, template: adomicile, onglet: adomicile }

app_femmes:
    path:      /quand-consulter/femmes-enceintes.html
    defaults:  { _controller: AppBundle:Default:index, template: femmes, onglet: femmes }

app_nourrissons:
    path:      /quand-consulter/nourrissons.html
    defaults:  { _controller: AppBundle:Default:index, template: nourrissons, onglet: nourrissons }

app_adolescents:
    path:      /quand-consulter/enfants-et-adolescents.html
    defaults:  { _controller: AppBundle:Default:index, template: adolescents, onglet: adolescents }

app_adultes:
    path:      /quand-consulter/adultes-et-seniors.html
    defaults:  { _controller: AppBundle:Default:index, template: adultes, onglet: adultes }

app_sportifs:
    path:      /quand-consulter/sportifs.html
    defaults:  { _controller: AppBundle:Default:index, template: sportifs, onglet: sportifs }
